# Generated by Django 4.1 on 2022-09-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='no category', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
